# Generated by Django 3.0.3 on 2020-02-14 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('eventLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(blank=True, max_length=255, null=True)),
                ('eventDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('userID', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('meetingdate', models.DateField()),
                ('meetingtime', models.CharField(blank=True, max_length=255, null=True)),
                ('meetinglocation', models.CharField(blank=True, max_length=255, null=True)),
                ('meetingAgenda', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'db_table': 'Meeting',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcename', models.CharField(blank=True, max_length=255, null=True)),
                ('resourcetype', models.CharField(blank=True, max_length=255, null=True)),
                ('resourceURL', models.URLField()),
                ('resourcedateEnter', models.TextField()),
                ('resourceDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingtext', models.TextField()),
                ('meetingAttendence', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('meetingID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.Meeting')),
            ],
            options={
                'db_table': 'meetingMinutes',
            },
        ),
    ]
