# Generated by Django 3.0.2 on 2020-02-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resourceURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
